version: "3.8"
services:
  patient-service:
    build:
      context: ./patient-service
      dockerfile: ../docker/Dockerfile.node
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  application-service:
    build:
      context: ./application-service
      dockerfile: ../docker/Dockerfile.node
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PATIENT_SERVICE_URL=http://patient-service:3001
    depends_on:
      - patient-service
